# This file configures the Dart analyzer (lint rules, warnings, etc.)

include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    prefer_const_constructors: warning

linter:
  rules:
    # 🔥 Const optimizations
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_const_declarations: true

    # 🧹 Optional (good practices)
    avoid_print: false
    # prefer_single_quotes: true